### ISSUE TITLE
.net 5.0 or framework 4.X

### ISSUE THREAD

**Issue by qtbui159** [AgoraIO-Extensions/Agora-C_Sharp-SDK#1]
If I modify the project directly to .net 5.0 or framework 4.X, will there be any pitfalls when I run it?

如果直接修改工程为 .net 5.0 或者 framework 4.X ，运行的时候会有什么坑吗？

**Comment by YiqingJackieHuang** [comment]
Our SDK supports **.NET 5.0**.

**Comment by faldor20-notes** [comment]
Not on nuget
