### ISSUE TITLE
Join a channel without media - only chat

### ISSUE THREAD

**Issue by Lopuch** [AgoraIO-Extensions/Agora-C_Sharp-SDK#109]
Hello,
I would like to join a channel without media and use the SendMessage functionality only. Use media on request lately.
I want to mimic RTM product.
In our usecase we do not need the media every time.
If there is a way how to use RTM (not RTC) with c#, please let me know.

**Comment by xiayangqun** [comment]
you can download rtm in this page
https://docs.agora.io/cn/Real-time-Messaging/downloads?platform=All%20Platforms
