### ISSUE TITLE
Issue while clicking on join channel

### ISSUE THREAD

**Issue by MayureshPra** [AgoraIO-Extensions/Agora-C_Sharp-SDK#169]
When I am selecting the join channel option it is giving error that unable to find entry point for CreateIrisRtcEngine method and AgoraRtcWrapper is not loading

  private AgoraRtcEngine(EngineType type = EngineType.kEngineTypeNormal)
        {
            _result = new CharAssistant();
            _channelInstance = new Dictionary<string, AgoraRtcChannel>();
            _irisRtcEngine = type == EngineType.kEngineTypeNormal
                ? AgoraRtcNative.CreateIrisRtcEngine()
                : AgoraRtcNative.CreateIrisRtcEngine(EngineType.kEngineTypeSubProcess);

**Comment by peilinok** [comment]
Would you please give us more informations? Such as the version of sdk、the target platform and so no。
