### ISSUE TITLE
110 error when screen share

### ISSUE THREAD

**Issue by leeyj1116yj** [AgoraIO-Extensions/Agora-C_Sharp-SDK#208]
Select tap "screen share" and press "join channel" and i got 110 error
also got 1042 warning

The message shows "join ok" but i don't think it's joined.
I think other function dosen't works either.

[error api](https://api-ref.agora.io/en/video-sdk/windows-csharp/3.x/API/error_rtc.html)
it says I need token-based authentication and i can't understand what it is.

I remember agora screen share in unity worked fine without token setting.

Any suggestion what to do?

Thank you.

**Comment by xiayangqun** [comment]
ERR_INVALID_TOKEN = 110,
  WARN_ADM_INCONSISTENT_AUDIO_DEVICE = 1042,
  
  may be you should check your token is available.
