### ISSUE TITLE
The demo is not working at all

### ISSUE THREAD

**Issue by Hoang-Minh** [AgoraIO-Extensions/Agora-C_Sharp-SDK#25]
I fill out the app id and channel name for the demo, but after joining, the screen is not showing anything.
Also, I notice that we don't have to fill in any token ? The demo that you have here https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/ does require it though.

**Comment by mberky** [comment]
There is no need to fill token in C#  API-Example, please use app id with no token.
https://sso2.agora.io/cn/login

**Comment by Hoang-Minh** [comment]
Hmm, the demo only works with app without token. Is there anyway that I can enforce it with a token on c# ? Thank you

**Comment by mberky** [comment]
https://github.com/AgoraIO/Agora-Unity-Quickstart/tree/master/API-Example-Unity/Assets/API-Example/examples/advanced/JoinChannelVideoToken
