### ISSUE TITLE
Error dynamic use static key

### ISSUE THREAD

**Issue by imtiazwazir** [AgoraIO-Extensions/Agora-C_Sharp-SDK#81]
Getting following error

Uncaught (in promise) AgoraRTCException: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: flag: 4096, message: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: dynamic use static key

I did use new key but no effect.

**Comment by Highbee4u** [comment]
@imtiazwazir Have you been able to resolve this? I am experiencing thesame error

**Comment by plutoless** [comment]
@imtiazwazir @Highbee4u could you pls share the code how you join channel? this error means you should use a dynamic generated token to join channel while you use a static one.

**Comment by Highbee4u** [comment]
> @imtiazwazir @Highbee4u could you pls share the code how you join channel? this error means you should use a dynamic generated token to join channel while you use a static one.

I am using there PHP class here (https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/php/sample)  and It generate token but the token but couldn't authenticate as it shows this error

**Comment by plutoless** [comment]
@Highbee4u the error basically indicates you are not using token at all. it does not even mean the token you generated is incorrect. could you pls share the code how you join channel?

**Comment by Highbee4u** [comment]
> @Highbee4u the error basically indicates you are not using token at all. it does not even mean the token you generated is incorrect. could you pls share the code how you join channel?

I am not the one responsible for that, I am only to generate token for Fontend people, but he most likely be using the sample code on the Agora Doc

**Comment by plutoless** [comment]
the first parameter of join should be the token you generated for him, instead of static APP_ID

**Comment by Highbee4u** [comment]
> the first parameter of join should be the token you generated for him, instead of static APP_ID

After changing the first parameter
<img width="437" alt="ice_screenshot_20220713-164017" src="https://user-images.githubusercontent.com/31209419/178787681-de3b45b4-8f80-46a6-b7c0-f73a9341971e.png">

this the response he got

**Comment by plutoless** [comment]
this means the token you generated is incorrect. how did you generate your token?

**Comment by Highbee4u** [comment]
> this means the token you generated is incorrect. how did you generate your token?

I have been able to resolved it, I modified the php class and also changes the time parameter. Thanks

**Comment by TIkTok593** [comment]
How did you solve the issue, please share that with me.
I noticed that you are doing it from Dennis's video on youtube, because it's similar to my code

**Comment by coderFeedForwardAlg** [comment]
When I got this error it was because my API key and app id was null because I did not set up my environment variables right. I hope this helps someone.

**Comment by tsantos-dev** [comment]
@p eu peguei o token do certificado primario porém pra mim ainda continua o mesmo erro que do colega
