### ISSUE TITLE
The Nuget only works on x86 targets

### ISSUE THREAD

**Issue by xultz** [AgoraIO-Extensions/Agora-C_Sharp-SDK#83]
Hello, I added the Nuget to a new project, and it only runs if I set the target of my project to x86. If I set to x64, it doesn't run, giving me an exception:
An unhandled exception of type 'System.BadImageFormatException' occurred in Host_Test_1.dll
Could not load file or assembly 'agorartc, Version=3.6.2.0, Culture=neutral, PublicKeyToken=null'. Trying to load a program in incorret format.

Is there a Nuget version of the library that runs on x64 targets?

**Comment by sbd021** [comment]
What is you app project architecture, .netCore, .netFramework or others?

**Comment by xultz** [comment]
Right now I'm using .Net 5.0
What is the recommended framework to work with the Agora library?

**Comment by sbd021** [comment]
APIExample in this repo is based on .netCore winform and support .netcore 2.0 or later.

**Comment by architpoddar-if** [comment]
@xultz Were you able to find a solution for this? I'm getting this same error. I have a WPF app targetting .NET Framework 4.8
